/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Language } from './types';

export const translations = {
  en: {
    appTitle: 'Premium Time Tracker',
    dashboard: 'Dashboard',
    projects: 'Projects',
    reports: 'Reports',
    settings: 'Settings',
    
    // Dashboard / Project cards
    startWorking: 'Start Working',
    pause: 'Pause',
    resume: 'Resume',
    stop: 'Stop',
    active: 'Active',
    paused: 'Paused',
    notRunning: 'Not Running',
    totalTimeWorked: 'Total Time Worked',
    noDescription: 'No description provided',
    hoursShort: 'h',
    minShort: 'm',
    secShort: 's',
    rateLabel: 'Hourly Rate',
    clientLabel: 'Client',
    statusLabel: 'Status',
    revenueEstimate: 'Estimated Revenue',
    
    // Project actions
    editProject: 'Edit Project',
    deleteProject: 'Delete Project',
    createProject: 'Create Project',
    confirmDelete: 'Are you sure you want to delete this project? All associated work sessions will be permanently lost.',
    
    // Form fields
    projectNameReq: 'Project Name (required)',
    projectName: 'Project Name',
    description: 'Description',
    descriptionOpt: 'Description (optional)',
    hourlyRateOpt: 'Hourly Rate (optional, currency)',
    clientNameOpt: 'Client Name (optional)',
    cancel: 'Cancel',
    save: 'Save',
    create: 'Create',
    
    // Reports
    reportsAndExport: 'Reports & Export',
    filterBy: 'Filter By',
    singleDay: 'Single Day',
    week: 'Week',
    month: 'Month',
    customRange: 'Custom Date Range',
    startDate: 'Start Date',
    endDate: 'End Date',
    summary: 'Summary',
    totalHours: 'Total Hours',
    sessionsCount: 'Sessions',
    avgDailyHours: 'Daily Avg Hours',
    estimatedIncome: 'Est. Revenue',
    detailedSessions: 'Detailed Sessions Table',
    date: 'Date',
    project: 'Project',
    hoursWorked: 'Hours Worked',
    startTimeTable: 'Start',
    endTimeTable: 'End',
    durationTable: 'Duration',
    exportToExcel: 'Export to Excel (XLSX)',
    exportSuccess: 'XLSX export initiated successfully!',
    noSessionsFound: 'No work sessions found matching the criteria.',
    allData: 'All Data',

    // Statistics Card
    statistics: 'Overall Stats',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    overall: 'Overall',

    // Settings
    language: 'Language',
    english: 'English',
    hebrew: 'Hebrew (עברית)',
    theme: 'Theme',
    light: 'Light Theme',
    dark: 'Dark Theme',
    systemDefault: 'System Default',
    appearance: 'Appearance Preset',
    blackWhitePremium: 'Black & White Premium',
    dataManagement: 'Data Management',
    exportDbText: 'Export Local Database',
    importDbText: 'Import Local Database',
    backupDataText: 'Generate Backup JSON',
    exportDbDesc: 'Save a backup of your local database.',
    importDbDesc: 'Restore database from a local backup file.',
    about: 'About',
    appVersion: 'App Version',
    privacyPolicy: 'Privacy Policy',
    privacyPolicyDesc: '100% local. Your data stays securely on your device, never uploaded to any server.',
    dbImportSuccess: 'Database imported successfully!',
    dbImportError: 'Invalid backup file format.',
    dbExportSuccess: 'Backup file downloaded successfully!',
    currencyLabel: 'Default Currency',
    overrideRateLabel: 'Override Hourly Rate',
    overrideRateDesc: 'Specify a custom hourly rate to instantly recalculate entire statistics dynamically.',
    viewPolicyBtn: 'View Complete Legal Policy',
    closePolicyBtn: 'Close Policy Statement',
    detailedTableSubtitle: 'See chronological logs of tracked sessions',

    // Platform Mock & Extras
    androidSimulator: 'Android Device Demo',
    codeExplorer: 'Kotlin/Compose Source Code Explorer',
    toggleFullScreen: 'Toggle Full Screen Web Layout',
    androidStudioReady: 'Android Studio Ready Project Folder',
    androidReadyDesc: 'A fully formatted Kotlin/Jetpack Compose Android project structure is pre-generated in the workspace and ready for export!',
    viewSourceBtn: 'View Compose Source',
    returnToDemo: 'Return to Simulator',
    emptyState_projects: 'No projects created yet. Click the "+" button below to start tracking your time.'
  },
  he: {
    appTitle: 'מעקב זמן יוקרתי',
    dashboard: 'לוח בקרה',
    projects: 'פרויקטים',
    reports: 'דוחות',
    settings: 'הגדרות',
    
    // Dashboard / Project cards
    startWorking: 'התחל עבודה',
    pause: 'השהה',
    resume: 'המשך',
    stop: 'עצור',
    active: 'פעיל',
    paused: 'מושהה',
    notRunning: 'לא פועל',
    totalTimeWorked: 'סך הכל זמן עבודה',
    noDescription: 'לא הוזן תיאור',
    hoursShort: 'שע׳',
    minShort: 'דק׳',
    secShort: 'שני׳',
    rateLabel: 'תעריף לשעה',
    clientLabel: 'לקוח',
    statusLabel: 'מצב',
    revenueEstimate: 'הכנסה משוערת',
    
    // Project actions
    editProject: 'עריכת פרויקט',
    deleteProject: 'מחיקת פרויקט',
    createProject: 'יצירת פרויקט',
    confirmDelete: 'האם אתה בטוח שברצונך למחוק פרויקט זה? כל מפגשי העבודה השייכים לו יימחקו לצמיתות.',
    
    // Form fields
    projectNameReq: 'שם הפרויקט (חובה)',
    projectName: 'שם הפרויקט',
    description: 'תיאור',
    descriptionOpt: 'תיאור (אופציונלי)',
    hourlyRateOpt: 'תעריף לשעה (אופציונלי)',
    clientNameOpt: 'שם הלקוח (אופציונלי)',
    cancel: 'ביטול',
    save: 'שמירה',
    create: 'צור',
    
    // Reports
    reportsAndExport: 'דוחות וייצוא',
    filterBy: 'סנן לפי',
    singleDay: 'יום בודד',
    week: 'שבוע',
    month: 'חודש',
    customRange: 'טווח תאריכים מותאם',
    startDate: 'תאריך התחלה',
    endDate: 'תאריך סיום',
    summary: 'סיכום נתונים',
    totalHours: 'סה״כ שעות',
    sessionsCount: 'מפגשים',
    avgDailyHours: 'ממוצע שעתי יומי',
    estimatedIncome: 'הכנסה משוערת',
    detailedSessions: 'טבלת מפגשים מפורטת',
    date: 'תאריך',
    project: 'פרויקט',
    hoursWorked: 'שעות עבודה',
    startTimeTable: 'התחלה',
    endTimeTable: 'סיום',
    durationTable: 'משך עבודה',
    exportToExcel: 'ייצוא לקובץ אקסל (XLSX)',
    exportSuccess: 'ייצוא לקובץ אקסל החל בהצלחה!',
    noSessionsFound: 'לא נמצאו מפגשי עבודה העונים לקריטריונים אלו.',
    allData: 'כל הנתונים',

    // Statistics Card
    statistics: 'סטטיסטיקות כלליות',
    today: 'היום',
    thisWeek: 'השבוע',
    thisMonth: 'החודש',
    overall: 'סה״כ כללי',

    // Settings
    language: 'שפה',
    english: 'אנגלית',
    hebrew: 'עברית (עברית)',
    theme: 'ערכת נושא',
    light: 'ערכת נושא בהירה',
    dark: 'ערכת נושא כהה',
    systemDefault: 'ברירת מחדל של המערכת',
    appearance: 'סגנון מראה',
    blackWhitePremium: 'שחור-לבן יוקרתי (מינימלי)',
    dataManagement: 'ניהול נתונים local-first',
    exportDbText: 'ייצוא בסיס נתונים מקומי',
    importDbText: 'ייבוא בסיס נתונים מקומי',
    backupDataText: 'יצירת קובץ גיבוי JSON',
    exportDbDesc: 'שמור קובץ גיבוי של בסיס הנתונים המקומי שלך.',
    importDbDesc: 'שחזר את בסיס הנתונים מקובץ גיבוי מקומי.',
    about: 'אודות האפליקציה',
    appVersion: 'גרסת אפליקציה',
    privacyPolicy: 'מדיניות פרטיות',
    privacyPolicyDesc: 'האפליקציה פועלת באופן מקומי מלא. המידע שלך אינו יוצא מהמכשיר ואינו נשלח לאף שרת חיצוני.',
    dbImportSuccess: 'בסיס הנתונים יובא בהצלחה!',
    dbImportError: 'פורמט קובץ הגיבוי אינו תקין.',
    dbExportSuccess: 'קובץ הגיבוי הורד בהצלחה למכשיר!',
    currencyLabel: 'מטבע ברירת מחדל',
    overrideRateLabel: 'עקיפת תעריף שעתי',
    overrideRateDesc: 'הזן תעריף שעתי מותאם אישית לעדכון מיידי של כל הדוחות במסך זה באופן דינמי.',
    viewPolicyBtn: 'הצג הצהרת פרטיות מלאה',
    closePolicyBtn: 'סגור מסמך משפטי',
    detailedTableSubtitle: 'צפה ברשומות כרונולוגיות של כל זמני העבודה שנמדדו',

    // Platform Mock & Extras
    androidSimulator: 'הדגמת מכשיר אנדרואיד',
    codeExplorer: 'סייר קוד המקור (Kotlin / Jetpack Compose)',
    toggleFullScreen: 'החלף לתצוגת דפדפן מלאה',
    androidStudioReady: 'תיקיית פרויקט מוכנה ל-Android Studio',
    androidReadyDesc: 'מבנה פרויקט אנדרואיד מלא ב-Kotlin ו-Jetpack Compose מוכן בתיקיית העבודה וממתין לייצוא!',
    viewSourceBtn: 'הצג קוד מקור Compose',
    returnToDemo: 'חזור לסימולטור',
    emptyState_projects: 'לא נוצרו פרויקטים עדיין. לחץ על כפתור ה-"+" למטה כדי להתחיל לעקוב אחר זמן העבודה שלך.'
  }
};
